Simulado Base Interna :=
	    IF(OR (    [Simulado Base Interna - origem] = "Não Informado";
           OR (        [Simulado Base Interna - origem] = "Registro Inválido";
               [Simulado Base Interna - origem] = "Unassigned"            )        );
       "Não";
       [Simulado Base Interna - origem])


$User :=
	dUser[Login]


Tipo Tag :=
	IF(SEARCH("#prioridademaxima";
           dRegistry[Tag],,BLANK()) > 0;
           "#PRIORIDADE MÁXIMA";
           IF(SEARCH("#NOTIFICACAO",dRegistry[Tag],,BLANK())>0, "#NOTIFICAÇÃO";
           IF(SEARCH("#NOTIFICAÇÃO",dRegistry[Tag],,BLANK())>0, "#NOTIFICAÇÃO";
           IF(AND(dRegistry[Flag Performace - origem] = 1,dRegistry[Flag Performace Encaminhada - origem]=1), "#PERFORMANCE";
           IF(SEARCH("#performance",dRegistry[Tag],,BLANK())>0, "#PERFORMANCE", "OUTRAS")))))


Versão Pai :=
	IF(dRegistry[Versão Original é: vazio];
   "Não Informado";
   IF(dRegistry[Versão Original é: >= 2];
       "Outros",                       LEFT(dRegistry[Versão Origem];
       5)))


Flag Bloqueado :=
	   IF(dRegistry[Bynary Flag Bloqueado] = 1, "Sim", "Não")


Versão Original é: vazio :=
	dRegistry[Versão Origem] = BLANK() // ssas processa mais rápido se as funções estão divididas (vide doc ssas)


Versão Original é: >= 2 :=
	LEN(dRegistry[Versão Origem]) <= 2


Bynary Flag Dia da Semana :=
	IF(dTempo[Flag Dia de Semana] = "S"	
, 1 
, 0 )


Bynary Flag Fim de Semana :=
	IF(dTempo[Flag Fim de Semana] = "S"	
, 1 
, 0 )


Bynary Flag Feriado :=
	IF(dTempo[Flag Feriado] = "S"	
, 1 
, 0 )


Mês Current :=
	IF(dTempo[Code Mês] = MONTH(TODAY())	
, 1 
, 0)


Ano Current :=
	IF(dTempo[Code Ano] = YEAR(TODAY())	
, 1 
, 0)


Período Current :=
	IF(dTempo[Mês Current] && dTempo[Ano Current];
    "Sim";
    "Não")


Ano IDDATA :=
	MID(factRegistry[IDDATA]	
, 1 
, 4)


Mês IDDATA :=
	MID(factRegistry[IDDATA], 5, 2)


Data IDDATA :=
	DATEVALUE(MID(factRegistry[IDDATA];
           1, 4)
	& "/" &
        MID(factRegistry[IDDATA];
           5, 2) 
	& "/" &
       MID(factRegistry[IDDATA];
           7, 2)    )


Mean Horas Apontadas por Registry :=
	   IF(AND([Ano IDDATA] == YEAR(TODAY()), [Mês IDDATA] == MONTH(TODAY()));
       factRegistry[Horas Apontadas];
       0)


Qtde Registry :=
	1


Prazo SLA Formatado :=
	IF(factSample[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK(),                        factSample[Data IDDTPRAZOSLA])


Data IDDTPRAZOSLA :=
	DATEVALUE(    MID(factSample[IDDTPRAZOSLA];
               1, 4)
	& "/" &
            MID(factSample[IDDTPRAZOSLA];
               5, 2) 
	& "/" &
           MID(factSample[IDDTPRAZOSLA];
               7, 2)        )


SLA Vencido :=
	IF(factBacklog[DateTime IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
   0,              IF(factBacklog[IDDTAPURACAO é: Ano e Mês Corrente];
       IF(factBacklog[DateTime IDDTPRAZOSLA] >= dTempo[DateTime Corrente];
           0;
           1);
       IF(factBacklog[DateTime IDDTPRAZOSLA] >= [DateTime IDDTAPURACAO];
           0;
           1)    ) )


Sem SLA :=
	IF(factBacklog[DateTime IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
   1;
   0)


SLA a Vencer :=
	     IF(factBacklog[DateTime IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
       0;
       IF(factBacklog[IDDTAPURACAO é: Ano e Mês Corrente];
           IF(factBacklog[DateTime IDDTPRAZOSLA] >= dTempo[DateTime Corrente];
               1;
               0);
           IF(factBacklog[DateTime IDDTPRAZOSLA] >= [DateTime IDDTAPURACAO];
               1;
               0)        )    )


DateTime IDDTAPURACAO :=
	DATEVALUE(MID(factBacklog[IDDTAPURACAO];
           1, 4)
	& "/" &
        MID(factBacklog[IDDTAPURACAO];
           5, 2) 
	& "/" &
       MID(factBacklog[IDDTAPURACAO];
           7, 2)    )


DateTime IDDTPRAZOSLA :=
	   MID(factBacklog[IDDTPRAZOSLA];
       1, 4)
	& "/" &
    MID(factBacklog[IDDTPRAZOSLA];
       5,2) 
	& "/" &
   MID(factBacklog[IDDTPRAZOSLA];
       7, 2) & " "&   factBacklog[IDHRPRAZOSLA]


Tipo SLA :=
	IF(factBacklog[DateTime IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
   "Sem SLA";
   IF(AND(MONTH(factBacklog[DateTime IDDTAPURACAO]) = MONTH(TODAY());
           factBacklog[DateTime IDDTAPURACAO] >= TODAY());
       "SLA a Vencer";
       IF(AND(MONTH(factBacklog[DateTime IDDTAPURACAO]) <> MONTH(TODAY());
           factBacklog[DateTime IDDTPRAZOSLA] >= factBacklog[DateTime IDDTAPURACAO]);
       "SLA a Vencer";
       "SLA Vencido")    ))


Prazo SLA Formatado :=
	IF(factBacklog[DateTime IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       factBacklog[DateTime IDDTPRAZOSLA])


DateTime IDDTPREVISTA :=
	   MID(factBacklog[IDDTPREVISTA];
           1, 4)
	& "/" &
        MID(factBacklog[IDDTPREVISTA];
           5, 2) 
	& "/" &
       MID(factBacklog[IDDTPREVISTA];
           7, 2) & " "&   factBacklog[IDHRPREVISTA]


IDDTAPURACAO é: Ano e Mês Corrente :=
	['IF( AND(MONTH(factBacklog[DateTime IDDTAPURACAO]) = dTempo[Mês Corrente],                       YEAR(factBacklog[DateTime IDDTAPURACAO]) = dTempo[Ano Corrente]), TRUE(), FALSE())


DateTime IDDTCRIACAO :=
	MID(factBacklog[IDDTCRIACAO];
           1, 4)
	& "/" &
    MID(factBacklog[IDDTCRIACAO];
           5, 2) 
	& "/" &
    MID(factBacklog[IDDTCRIACAO];
           7, 2) & " "&   factBacklog[IDHRCRIACAO]


DateTime IDDTCRIACAOSAC :=
	   MID(factBacklog[IDDTCRIACAOSAC];
           1, 4)
	& "/" &
        MID(factBacklog[IDDTCRIACAOSAC];
           5, 2) 
	& "/" &
       MID(factBacklog[IDDTCRIACAOSAC];
           7, 2)


Idade Backlog :=
	DATEDIFF(factBacklog[DateTime IDDTCRIACAOSAC], [DateTime Corrente], DAY)


Data IDDTPRAZOSLA :=
	   DATEVALUE(MID(factInput[IDDTPRAZOSLA];
           1, 4)
	& "/" &
        MID(factInput[IDDTPRAZOSLA];
           5, 2) 
	& "/" &
       MID(factInput[IDDTPRAZOSLA];
           7, 2)    )


Prazo SLA Formatado :=
	IF(factInput[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       factInput[Data IDDTPRAZOSLA])


SLA Venceu no Suporte :=
	   IF(factInput[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
       0;
       IF(factInput[Data IDDTPRAZOSLA] <= factInput[Data IDDTCRIACAO];
           1;
           0)        ) 


Data IDDTCRIACAO :=
	   DATEVALUE(MID(factInput[IDDTCRIACAO];
           1, 4)
	& "/" &
        MID(factInput[IDDTCRIACAO];
           5, 2) 
	& "/" &
       MID(factInput[IDDTCRIACAO];
           7, 2)    )


Data IDDTCRIACAOSAC :=
	   MID(factInput[IDDTCRIACAOSAC];
           1, 4)
	& "/" &
        MID(factInput[IDDTCRIACAOSAC];
           5, 2) 
	& "/" &
       MID(factInput[IDDTCRIACAOSAC];
           7, 2)


Tempo Suporte Aux :=
	DATEDIFF(factInput[Data IDDTCRIACAOSAC Tratado Valores Nulos], factInput[Data IDDTCRIACAO],DAY)


Data IDDTCRIACAOSAC Tratado Valores Nulos :=
	IF(OR(OR(factInput[Data IDDTCRIACAOSAC] == DATEVALUE("01/01/1900"), (factInput[Data IDDTCRIACAOSAC] == DATEVALUE("02/01/1900"))), factInput[Data IDDTCRIACAOSAC] > [DateTime Corrente]);
                      BLANK();
                       factInput[Data IDDTCRIACAOSAC]) // desta forma sempre retorna um valor negativo. Depois trato em outra medida


Tempo Suporte :=
	IF(factInput[Tempo Suporte Aux] > 0, factInput[Tempo Suporte Aux], 0)


Data IDDTPRAZOSLA :=
	   DATEVALUE(MID(factNegociado[IDDTPRAZOSLA];
           1, 4)
	& "/" &
        MID(factNegociado[IDDTPRAZOSLA];
           5, 2) 
	& "/" &
       MID(factNegociado[IDDTPRAZOSLA];
           7, 2)    )


Prazo SLA Formatado :=
	IF(factNegociado[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       factNegociado[Data IDDTPRAZOSLA])


Tipo Negociação :=
	IF(SEARCH("#negociadospoc", RELATED(dRegistry[tag]),BLANK()) > 0;
       "#NEGOCIADOSPOC";
       IF(SEARCH("#negociadoaustralia", RELATED(dRegistry[tag]),BLANK()) > 0;
           "#NEGOCIADOAUSTRALIA";
           IF(factNegociado[IDFASECICLO] = 12;
               "#ULTIMAMILHA";
               IF(SEARCH("#prioridademaxima", RELATED(dRegistry[tag]),BLANK()) > 0;
                   "#PRIORIDADE MÁXIMA";
                   IF(SEARCH("#NOTIFICACAO", RELATED(dRegistry[tag]),BLANK()) > 0;
                       "#NOTIFICAÇÃO";
                       IF(SEARCH("#NOTIFICAÇÃO", RELATED(dRegistry[tag]),BLANK()) > 0;
                           "#NOTIFICAÇÃO";
                           IF(SEARCH("#ULTIMAMILHA", RELATED(dRegistry[tag]), ,BLANK()) > 0;
                               "#ULTIMAMILHA";
                               "OUTRAS"                            )                        )                    )                )            )        )    )


Entregue Cliente :=
	   IF(SEARCH("#prontocliente";
       RELATED(dRegistry[tag]),BLANK()) > 0;
       "Sim";
       "Não")


DateTime IDDTRESOLUCAO :=
	       MID(factOutput[IDDTRESOLUCAO];
           1, 4)
	& "/" &
        MID(factOutput[IDDTRESOLUCAO];
           5, 2) 
	& "/" &
       MID(factOutput[IDDTRESOLUCAO];
           7, 2) & " "&        [IDHRRESOLUCAO]


No Prazo :=
	   IF(factOutput[Data IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
       1;
       IF(factOutput[IDFASECICLO] = 5;
           1;
           IF(factOutput[IDFASECICLO] = 11;
               1;
               IF(factOutput[IDFASECICLO] = 19;
                   1;
                   IF(factOutput[DateTime IDDTRESOLUCAO] <= factOutput[Data IDDTPRAZOSLA];
                       1;
                       0)                )            )        )     )


Fora Prazo :=
	IF(factOutput[No Prazo]=1, 0	
, 1 
)


Data IDDTPRAZOSLA :=
	       MID(factOutput[IDDTPRAZOSLA];
           1, 4)
	& "/" &
        MID(factOutput[IDDTPRAZOSLA];
           5, 2) 
	& "/" &
       MID(factOutput[IDDTPRAZOSLA];
           7, 2) & " "&    [IDHRPRAZOSLA]


Prazo SLA Formatado :=
	IF(factOutput[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       factOutput[Data IDDTPRAZOSLA])


IDDTAPURACAO Manipulado :=
	IF([Qtde Delivery] > 0, [IDDTAPURACAO], BLANK())


DateTime IDDTCRIACAOSAC :=
	   MID(factOutput[IDDTCRIACAOSAC];
           1, 4)
	& "/" &
        MID(factOutput[IDDTCRIACAOSAC];
           5, 2) 
	& "/" &
       MID(factOutput[IDDTCRIACAOSAC];
           7, 2)


Tempo Solução Aux :=
	DATEDIFF(factOutput[Data IDDTCRIACAOSAC com Vazio], factOutput[DateTime IDDTRESOLUCAO], DAY)


Data IDDTCRIACAOSAC :=
	   DATEVALUE(MID(factOutput[IDDTCRIACAOSAC];
           1, 4)
	& "/" &
        MID(factOutput[IDDTCRIACAOSAC];
           5, 2) 
	& "/" &
       MID(factOutput[IDDTCRIACAOSAC];
           7, 2)    )


Data IDDTCRIACAOSAC com Vazio :=
	IF(OR(OR(factOutput[Data IDDTCRIACAOSAC] == DATEVALUE("01/01/1900"), (factOutput[Data IDDTCRIACAOSAC] == DATEVALUE("02/01/1900"))), factOutput[DateTime IDDTCRIACAOSAC] > [DateTime Corrente]);
                      TODAY();
                       factOutput[Data IDDTCRIACAOSAC]) // desta forma sempre retorna um valor negativo. Depois trato em outra medida


Data IDDTRESOLUCAO :=
	       MID(factOutput[IDDTRESOLUCAO];
           1, 4)
	& "/" &
        MID(factOutput[IDDTRESOLUCAO];
           5, 2) 
	& "/" &
       MID(factOutput[IDDTRESOLUCAO];
           7, 2)


Tempo Solução :=
	IF(factOutput[Tempo Solução Aux] > 0, factOutput[Tempo Solução Aux], 0)


Tempo Gasto :=
	IF(CALCULATE(SUM(dTempo[Bynary Flag Dia da Semana]);
                           DATESBETWEEN(dTempo[Data];
                                       factTempoMedio[Data IDDTINICIOSTATUS];
                                       factTempoMedio[Data IDDTFINALSTATUS])) = 0;
               0;
               CALCULATE(SUM(dTempo[Bynary Flag Dia da Semana]);
                           DATESBETWEEN(dTempo[Data];
                                       factTempoMedio[Data IDDTINICIOSTATUS];
                                       factTempoMedio[Data IDDTFINALSTATUS])) - 1)


Data IDDTINICIOSTATUS :=
	   DATEVALUE(MID(factTempoMedio[IDDTINICIOSTATUS];
           1, 4)
	& "/" &
        MID(factTempoMedio[IDDTINICIOSTATUS];
           5, 2) 
	& "/" &
       MID(factTempoMedio[IDDTINICIOSTATUS];
           7, 2)    )


Data IDDTFINALSTATUS :=
	   DATEVALUE(MID(factTempoMedio[IDDTFINALSTATUS];
           1, 4)
	& "/" &
        MID(factTempoMedio[IDDTFINALSTATUS];
           5, 2) 
	& "/" &
       MID(factTempoMedio[IDDTFINALSTATUS];
           7, 2)    )


Diferença Dias Status :=
	DATEDIFF(factTempoMedio[Data IDDTINICIOSTATUS], factTempoMedio[Data IDDTFINALSTATUS], DAY)


dstatuschamado_status_chamado :=
	LOOKUPVALUE(dStatusChamado[Status Chamado], dStatusChamado[IDSTATUSCHAMADO], factTempoMedio[IDSTATUSCHAMADOANTERIOR])


Agrupador de Status :=
	IF(factTempoMedio[dstatuschamado_status_chamado] = "New";
       "Backlog";
       IF(factTempoMedio[dstatuschamado_status_chamado]="Ready for Dev";
           "Backlog";
           IF(factTempoMedio[dstatuschamado_status_chamado]="Backlog";
               "Backlog";
               IF(factTempoMedio[dstatuschamado_status_chamado]="Ag CodIFicação";
                   "Backlog";
                   IF(factTempoMedio[dstatuschamado_status_chamado]="Em Análise";
                       "Análise";
                       IF(factTempoMedio[dstatuschamado_status_chamado]="In-Progress";
                           "CodIFicação";
                           IF(factTempoMedio[dstatuschamado_status_chamado]="Needs-CodeQA";
                               "CodIFicação";
                               IF(factTempoMedio[dstatuschamado_status_chamado]="In-CodeQA";
                                   "CodIFicação";
                                   IF(factTempoMedio[dstatuschamado_status_chamado]="Needs Validation";
                                       "CodIFicação";
                                       IF(factTempoMedio[dstatuschamado_status_chamado]="Validation";
                                           "CodIFicação";
                                           IF(factTempoMedio[dstatuschamado_status_chamado]="Em CodIFicação";
                                               "CodIFicação";
                                               IF(factTempoMedio[dstatuschamado_status_chamado]="Ag Revisão";
                                                   "CodIFicação";
                                                   IF(factTempoMedio[dstatuschamado_status_chamado]="Em Revisão";
                                                       "CodIFicação";
                                                       IF(factTempoMedio[dstatuschamado_status_chamado]="Ag Sincronização";
                                                           "CodIFicação";
                                                           IF(factTempoMedio[dstatuschamado_status_chamado]="Em Sincronização";
                                                               "CodIFicação";
                                                               IF(factTempoMedio[dstatuschamado_status_chamado]="Em Validação Final";
                                                                   "CodIFicação";
                                                                   IF(factTempoMedio[dstatuschamado_status_chamado]="In Sinc";
                                                                       "CodIFicação";
                                                                       IF(factTempoMedio[dstatuschamado_status_chamado]="Revisado";
                                                                           "CodIFicação";
                                                                           IF(factTempoMedio[dstatuschamado_status_chamado]="Ag CodIFicação (Retorno PML)";
                                                                               "Ag. CodIFicação (já iniciado)";
                                                                               IF(factTempoMedio[dstatuschamado_status_chamado]="Ag CodIFicação (Retorno Suporte)";
                                                                                   "Ag. CodIFicação (já iniciado)";
                                                                                   IF(factTempoMedio[dstatuschamado_status_chamado]="Not Approved";
                                                                                       "Ag. CodIFicação (já iniciado)";
                                                                                           IF(factTempoMedio[dstatuschamado_status_chamado]="Reprovado";
                                                                                               "Ag. CodIFicação (já iniciado)";
                                                                                               IF(factTempoMedio[dstatuschamado_status_chamado]="Aprovado / Ag Fechamento";
                                                                                                   "Ag. Lib. Versão";
                                                                                                   IF(factTempoMedio[dstatuschamado_status_chamado]="Ag PML";
                                                                                                       "Ag. PML";
                                                                                                       IF(factTempoMedio[dstatuschamado_status_chamado]="Ag Suporte";
                                                                                                           "Ag. Suporte";
                                                                                                           IF(factTempoMedio[dstatuschamado_status_chamado]="Waiting Support";
                                                                                                               "Ag. Suporte";
                                                                                                               IF(factTempoMedio[dstatuschamado_status_chamado]="Ag Versões";
                                                                                                                   "Ag. Versão";
                                                                                                                   IF(factTempoMedio[dstatuschamado_status_chamado]="Needs Version";
                                                                                                                       "Ag. Versão";
                                                                                                                       IF(factTempoMedio[dstatuschamado_status_chamado]="Ag Teste Master";
                                                                                                                           "Ag. Teste";
                                                                                                                           IF(factTempoMedio[dstatuschamado_status_chamado]="Ag Teste Local";
                                                                                                                               "Ag. Teste";
                                                                                                                               IF(factTempoMedio[dstatuschamado_status_chamado]="Ag Validação Final";
                                                                                                                                   "Ag. Teste";
                                                                                                                                   IF(factTempoMedio[dstatuschamado_status_chamado]="Needs-VerIFication";
                                                                                                                                       "Ag. Teste";
                                                                                                                                       IF(factTempoMedio[dstatuschamado_status_chamado]="Blocked";
                                                                                                                                           "Bloqueado";
                                                                                                                                           IF(factTempoMedio[dstatuschamado_status_chamado]="Em Teste Master";
                                                                                                                                               "Teste";
                                                                                                                                               IF(factTempoMedio[dstatuschamado_status_chamado]="Em Teste Local";
                                                                                                                                                   "Teste";
                                                                                                                                                   IF(factTempoMedio[dstatuschamado_status_chamado]="In-Test";
                                                                                                                                                       "Teste";
                                                                                                                                                       "Pronto")                                                                                                                                                )                                                                                                                                            )                                                                                                                                        )                                                                                                                                    )                                                                                                                                )                                                                                                                            )                                                                                                                        )                                                                                                                    )                                                                                                                )                                                                                                            )                                                                                                        )                                                                                                    )                                                                                                )                                                                                            )                                                                                        )                                                                                    )                                                                                )                                                                            )                                                                        )                                                                    )                                                                )                                                            )                                                        )                                                    )                                                )                                            )                                        )                                    )                                )                            )                        )                    )                )            )        )


Data IDDTPRAZOSLA :=
	   DATEVALUE(MID(factBacklogZero[IDDTPRAZOSLA];
           1, 4)
	& "/" &
        MID(factBacklogZero[IDDTPRAZOSLA];
           5, 2) 
	& "/" &
       MID(factBacklogZero[IDDTPRAZOSLA];
           7, 2)    )


Prazo SLA Formatado :=
	IF(factBacklogZero[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       factBacklogZero[Data IDDTPRAZOSLA])


Período Current :=
	IF(dTempoApuracao[Mês Current] && dTempoApuracao[Bynary Ano Current];
    "Sim";
    "Não")


Mês Current :=
	IF(dTempoApuracao[Code Mês] = dTempo[Mês Corrente]	
, 1 
, 0)


Bynary Ano Current :=
	IF(dTempoApuracao[Code Ano] = dTempo[Ano Corrente]	
, 1 
, 0)


Bynary Flag Dia da Semana :=
	IF(dTempoApuracao[Flag Dia de Semana] = "S"	
, 1 
, 0)


Semana por Extenso :=
	[Descrição Semana Mês] //solicitação Carol


Semana que Passou ? :=
	IF([Número Semana Ano] < [Semana Current] && [Code Ano] = YEAR(TODAY());
       "Sim";
       IF([Code Ano] <  YEAR(TODAY());
           "Sim";
           "Não")    )


Semana Current ? :=
	   IF([Número Semana Ano] = [Semana Current] && [Code Ano] = YEAR(TODAY());
       "Sim";
       "Não")


Próxima Semana ? :=
	IF([Número Semana Ano] > [Semana Current] && [Code Ano] = YEAR(TODAY());
       "Sim";
       "Não")


Semana Por Extenso :=
	[Descrição Semana Mês] //solicitação Carol


Bynary Flag Dia da Semana :=
	IF(dTempoRegistry[Flag Dia de Semana] = "S"	
, 1 
, 0 )


Quatidade Registry :=
	1


Mean Horas Apontadas por Registry :=
	IF(AND(INT(MID(factRegistryPerfilSeguranca[IDDATA]	
, 1 
, 4)) == YEAR(TODAY());
       INT(MID(factRegistryPerfilSeguranca[IDDATA], 5, 2)) == MONTH(TODAY()));
   factRegistryPerfilSeguranca[Horas Apontadas - Origem];
   0)


Sigla Equipe Usuário :=
	[Equipe Usuário]


