Simulado Base Interna :=
	    IF(OR (    [Simulado Base Interna - origem] = "Não Informado";
           OR (        [Simulado Base Interna - origem] = "Registro Inválido";
               [Simulado Base Interna - origem] = "Unassigned"            )        );
       "Não";
       [Simulado Base Interna - origem])


$USUARIO :=
	dUsuario[Login]


Tipo Tag :=
	IF(SEARCH("#prioridademaxima";
           dChamado[Tag],,BLANK()) > 0;
           "#PRIORIDADE MÁXIMA";
           IF(SEARCH("#NOTIFICACAO",dChamado[Tag],,BLANK())>0, "#NOTIFICAÇÃO";
           IF(SEARCH("#NOTIFICAÇÃO",dChamado[Tag],,BLANK())>0, "#NOTIFICAÇÃO";
           IF(AND(dChamado[Flag Performace - origem] = 1,dChamado[Flag Performace Encaminhada - origem]=1), "#PERFORMANCE";
           IF(SEARCH("#performance",dChamado[Tag],,BLANK())>0, "#PERFORMANCE", "OUTRAS")))))


Versão Pai :=
	IF(dChamado[Versão Original é: vazio];
   "Não Informado";
   IF(dChamado[Versão Original é: >= 2];
       "Outros",                       LEFT(dChamado[Versão Origem];
       5)))


Flag Bloqueado :=
	   IF(dChamado[Binário Flag Bloqueado] = 1, "Sim", "Não")


Versão Original é: vazio :=
	dChamado[Versão Origem] = BLANK() // ssas processa mais rápido se as funções estão divididas (vide doc ssas)


Versão Original é: >= 2 :=
	LEN(dChamado[Versão Origem]) <= 2


Binário Flag Dia da Semana :=
	IF(dTempo[Flag Dia de Semana] = "S"	
, 1 
, 0 )


Binário Flag Fim de Semana :=
	IF(dTempo[Flag Fim de Semana] = "S"	
, 1 
, 0 )


Binário Flag Feriado :=
	IF(dTempo[Flag Feriado] = "S"	
, 1 
, 0 )


Mês Atual :=
	IF(dTempo[Código Mês] = MONTH(TODAY())	
, 1 
, 0)


Ano Atual :=
	IF(dTempo[Código Ano] = YEAR(TODAY())	
, 1 
, 0)


Período Atual :=
	IF(dTempo[Mês Atual] && dTempo[Ano Atual];
    "Sim";
    "Não")


Ano IDDATA :=
	MID(fChamadoApontamento[IDDATA]	
, 1 
, 4)


Mês IDDATA :=
	MID(fChamadoApontamento[IDDATA], 5, 2)


Data IDDATA :=
	DATEVALUE(MID(fChamadoApontamento[IDDATA];
           1, 4)
	& "/" &
        MID(fChamadoApontamento[IDDATA];
           5, 2) 
	& "/" &
       MID(fChamadoApontamento[IDDATA];
           7, 2)    )


Média Horas Apontadas por Apontamento :=
	   IF(AND([Ano IDDATA] == YEAR(TODAY()), [Mês IDDATA] == MONTH(TODAY()));
       fChamadoApontamento[Horas Apontadas];
       0)


Qtde Apontamento :=
	1


Prazo SLA Formatado :=
	IF(fChamadoArtefatoEvolucao[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK(),                        fChamadoArtefatoEvolucao[Data IDDTPRAZOSLA])


Data IDDTPRAZOSLA :=
	DATEVALUE(    MID(fChamadoArtefatoEvolucao[IDDTPRAZOSLA];
               1, 4)
	& "/" &
            MID(fChamadoArtefatoEvolucao[IDDTPRAZOSLA];
               5, 2) 
	& "/" &
           MID(fChamadoArtefatoEvolucao[IDDTPRAZOSLA];
               7, 2)        )


SLA Vencido :=
	IF(fChamadoBacklog[Data e Horário IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
   0,              IF(fChamadoBacklog[IDDTAPURACAO é: Ano e Mês Corrente];
       IF(fChamadoBacklog[Data e Horário IDDTPRAZOSLA] >= dTempo[Data e Horário Corrente];
           0;
           1);
       IF(fChamadoBacklog[Data e Horário IDDTPRAZOSLA] >= [Data e Horário IDDTAPURACAO];
           0;
           1)    ) )


Sem SLA :=
	IF(fChamadoBacklog[Data e Horário IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
   1;
   0)


SLA a Vencer :=
	     IF(fChamadoBacklog[Data e Horário IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
       0;
       IF(fChamadoBacklog[IDDTAPURACAO é: Ano e Mês Corrente];
           IF(fChamadoBacklog[Data e Horário IDDTPRAZOSLA] >= dTempo[Data e Horário Corrente];
               1;
               0);
           IF(fChamadoBacklog[Data e Horário IDDTPRAZOSLA] >= [Data e Horário IDDTAPURACAO];
               1;
               0)        )    )


Data e Horário IDDTAPURACAO :=
	DATEVALUE(MID(fChamadoBacklog[IDDTAPURACAO];
           1, 4)
	& "/" &
        MID(fChamadoBacklog[IDDTAPURACAO];
           5, 2) 
	& "/" &
       MID(fChamadoBacklog[IDDTAPURACAO];
           7, 2)    )


Data e Horário IDDTPRAZOSLA :=
	   MID(fChamadoBacklog[IDDTPRAZOSLA];
       1, 4)
	& "/" &
    MID(fChamadoBacklog[IDDTPRAZOSLA];
       5,2) 
	& "/" &
   MID(fChamadoBacklog[IDDTPRAZOSLA];
       7, 2) & " "&   fChamadoBacklog[IDHRPRAZOSLA]


Tipo SLA :=
	IF(fChamadoBacklog[Data e Horário IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
   "Sem SLA";
   IF(AND(MONTH(fChamadoBacklog[Data e Horário IDDTAPURACAO]) = MONTH(TODAY());
           fChamadoBacklog[Data e Horário IDDTAPURACAO] >= TODAY());
       "SLA a Vencer";
       IF(AND(MONTH(fChamadoBacklog[Data e Horário IDDTAPURACAO]) <> MONTH(TODAY());
           fChamadoBacklog[Data e Horário IDDTPRAZOSLA] >= fChamadoBacklog[Data e Horário IDDTAPURACAO]);
       "SLA a Vencer";
       "SLA Vencido")    ))


Prazo SLA Formatado :=
	IF(fChamadoBacklog[Data e Horário IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       fChamadoBacklog[Data e Horário IDDTPRAZOSLA])


Data e Horário IDDTPREVISTA :=
	   MID(fChamadoBacklog[IDDTPREVISTA];
           1, 4)
	& "/" &
        MID(fChamadoBacklog[IDDTPREVISTA];
           5, 2) 
	& "/" &
       MID(fChamadoBacklog[IDDTPREVISTA];
           7, 2) & " "&   fChamadoBacklog[IDHRPREVISTA]


IDDTAPURACAO é: Ano e Mês Corrente :=
	['IF( AND(MONTH(fChamadoBacklog[Data e Horário IDDTAPURACAO]) = dTempo[Mês Corrente],                       YEAR(fChamadoBacklog[Data e Horário IDDTAPURACAO]) = dTempo[Ano Corrente]), TRUE(), FALSE())


Data e Horário IDDTCRIACAO :=
	MID(fChamadoBacklog[IDDTCRIACAO];
           1, 4)
	& "/" &
    MID(fChamadoBacklog[IDDTCRIACAO];
           5, 2) 
	& "/" &
    MID(fChamadoBacklog[IDDTCRIACAO];
           7, 2) & " "&   fChamadoBacklog[IDHRCRIACAO]


Data e Horário IDDTCRIACAOSAC :=
	   MID(fChamadoBacklog[IDDTCRIACAOSAC];
           1, 4)
	& "/" &
        MID(fChamadoBacklog[IDDTCRIACAOSAC];
           5, 2) 
	& "/" &
       MID(fChamadoBacklog[IDDTCRIACAOSAC];
           7, 2)


Idade Backlog :=
	DATEDIFF(fChamadoBacklog[Data e Horário IDDTCRIACAOSAC], [Data e Horário Corrente], DAY)


Data IDDTPRAZOSLA :=
	   DATEVALUE(MID(fChamadoEntrada[IDDTPRAZOSLA];
           1, 4)
	& "/" &
        MID(fChamadoEntrada[IDDTPRAZOSLA];
           5, 2) 
	& "/" &
       MID(fChamadoEntrada[IDDTPRAZOSLA];
           7, 2)    )


Prazo SLA Formatado :=
	IF(fChamadoEntrada[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       fChamadoEntrada[Data IDDTPRAZOSLA])


SLA Venceu no Suporte :=
	   IF(fChamadoEntrada[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
       0;
       IF(fChamadoEntrada[Data IDDTPRAZOSLA] <= fChamadoEntrada[Data IDDTCRIACAO];
           1;
           0)        ) 


Data IDDTCRIACAO :=
	   DATEVALUE(MID(fChamadoEntrada[IDDTCRIACAO];
           1, 4)
	& "/" &
        MID(fChamadoEntrada[IDDTCRIACAO];
           5, 2) 
	& "/" &
       MID(fChamadoEntrada[IDDTCRIACAO];
           7, 2)    )


Data IDDTCRIACAOSAC :=
	   MID(fChamadoEntrada[IDDTCRIACAOSAC];
           1, 4)
	& "/" &
        MID(fChamadoEntrada[IDDTCRIACAOSAC];
           5, 2) 
	& "/" &
       MID(fChamadoEntrada[IDDTCRIACAOSAC];
           7, 2)


Tempo Suporte Aux :=
	DATEDIFF(fChamadoEntrada[Data IDDTCRIACAOSAC Tratado Valores Nulos], fChamadoEntrada[Data IDDTCRIACAO],DAY)


Data IDDTCRIACAOSAC Tratado Valores Nulos :=
	IF(OR(OR(fChamadoEntrada[Data IDDTCRIACAOSAC] == DATEVALUE("01/01/1900"), (fChamadoEntrada[Data IDDTCRIACAOSAC] == DATEVALUE("02/01/1900"))), fChamadoEntrada[Data IDDTCRIACAOSAC] > [Data e Horário Corrente]);
                      BLANK();
                       fChamadoEntrada[Data IDDTCRIACAOSAC]) // desta forma sempre retorna um valor negativo. Depois trato em outra medida


Tempo Suporte :=
	IF(fChamadoEntrada[Tempo Suporte Aux] > 0, fChamadoEntrada[Tempo Suporte Aux], 0)


Data IDDTPRAZOSLA :=
	   DATEVALUE(MID(fChamadoNegociado[IDDTPRAZOSLA];
           1, 4)
	& "/" &
        MID(fChamadoNegociado[IDDTPRAZOSLA];
           5, 2) 
	& "/" &
       MID(fChamadoNegociado[IDDTPRAZOSLA];
           7, 2)    )


Prazo SLA Formatado :=
	IF(fChamadoNegociado[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       fChamadoNegociado[Data IDDTPRAZOSLA])


Tipo Negociação :=
	IF(SEARCH("#negociadospoc", RELATED(dChamado[tag]),BLANK()) > 0;
       "#NEGOCIADOSPOC";
       IF(SEARCH("#negociadoaustralia", RELATED(dChamado[tag]),BLANK()) > 0;
           "#NEGOCIADOAUSTRALIA";
           IF(fChamadoNegociado[IDFASECICLO] = 12;
               "#ULTIMAMILHA";
               IF(SEARCH("#prioridademaxima", RELATED(dChamado[tag]),BLANK()) > 0;
                   "#PRIORIDADE MÁXIMA";
                   IF(SEARCH("#NOTIFICACAO", RELATED(dChamado[tag]),BLANK()) > 0;
                       "#NOTIFICAÇÃO";
                       IF(SEARCH("#NOTIFICAÇÃO", RELATED(dChamado[tag]),BLANK()) > 0;
                           "#NOTIFICAÇÃO";
                           IF(SEARCH("#ULTIMAMILHA", RELATED(dChamado[tag]), ,BLANK()) > 0;
                               "#ULTIMAMILHA";
                               "OUTRAS"                            )                        )                    )                )            )        )    )


Entregue Cliente :=
	   IF(SEARCH("#prontocliente";
       RELATED(dChamado[tag]),BLANK()) > 0;
       "Sim";
       "Não")


Data e Horário IDDTRESOLUCAO :=
	       MID(fChamadoSaida[IDDTRESOLUCAO];
           1, 4)
	& "/" &
        MID(fChamadoSaida[IDDTRESOLUCAO];
           5, 2) 
	& "/" &
       MID(fChamadoSaida[IDDTRESOLUCAO];
           7, 2) & " "&        [IDHRRESOLUCAO]


No Prazo :=
	   IF(fChamadoSaida[Data IDDTPRAZOSLA] = DATEVALUE("01/01/1900");
       1;
       IF(fChamadoSaida[IDFASECICLO] = 5;
           1;
           IF(fChamadoSaida[IDFASECICLO] = 11;
               1;
               IF(fChamadoSaida[IDFASECICLO] = 19;
                   1;
                   IF(fChamadoSaida[Data e Horário IDDTRESOLUCAO] <= fChamadoSaida[Data IDDTPRAZOSLA];
                       1;
                       0)                )            )        )     )


Fora Prazo :=
	IF(fChamadoSaida[No Prazo]=1, 0	
, 1 
)


Data IDDTPRAZOSLA :=
	       MID(fChamadoSaida[IDDTPRAZOSLA];
           1, 4)
	& "/" &
        MID(fChamadoSaida[IDDTPRAZOSLA];
           5, 2) 
	& "/" &
       MID(fChamadoSaida[IDDTPRAZOSLA];
           7, 2) & " "&    [IDHRPRAZOSLA]


Prazo SLA Formatado :=
	IF(fChamadoSaida[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       fChamadoSaida[Data IDDTPRAZOSLA])


IDDTAPURACAO Manipulado :=
	IF([Qtde Entregas] > 0, [IDDTAPURACAO], BLANK())


Data e Horário IDDTCRIACAOSAC :=
	   MID(fChamadoSaida[IDDTCRIACAOSAC];
           1, 4)
	& "/" &
        MID(fChamadoSaida[IDDTCRIACAOSAC];
           5, 2) 
	& "/" &
       MID(fChamadoSaida[IDDTCRIACAOSAC];
           7, 2)


Tempo Solução Aux :=
	DATEDIFF(fChamadoSaida[Data IDDTCRIACAOSAC com Vazio], fChamadoSaida[Data e Horário IDDTRESOLUCAO], DAY)


Data IDDTCRIACAOSAC :=
	   DATEVALUE(MID(fChamadoSaida[IDDTCRIACAOSAC];
           1, 4)
	& "/" &
        MID(fChamadoSaida[IDDTCRIACAOSAC];
           5, 2) 
	& "/" &
       MID(fChamadoSaida[IDDTCRIACAOSAC];
           7, 2)    )


Data IDDTCRIACAOSAC com Vazio :=
	IF(OR(OR(fChamadoSaida[Data IDDTCRIACAOSAC] == DATEVALUE("01/01/1900"), (fChamadoSaida[Data IDDTCRIACAOSAC] == DATEVALUE("02/01/1900"))), fChamadoSaida[Data e Horário IDDTCRIACAOSAC] > [Data e Horário Corrente]);
                      TODAY();
                       fChamadoSaida[Data IDDTCRIACAOSAC]) // desta forma sempre retorna um valor negativo. Depois trato em outra medida


Data IDDTRESOLUCAO :=
	       MID(fChamadoSaida[IDDTRESOLUCAO];
           1, 4)
	& "/" &
        MID(fChamadoSaida[IDDTRESOLUCAO];
           5, 2) 
	& "/" &
       MID(fChamadoSaida[IDDTRESOLUCAO];
           7, 2)


Tempo Solução :=
	IF(fChamadoSaida[Tempo Solução Aux] > 0, fChamadoSaida[Tempo Solução Aux], 0)


Tempo Gasto :=
	IF(CALCULATE(SUM(dTempo[Binário Flag Dia da Semana]);
                           DATESBETWEEN(dTempo[Data];
                                       fChamadoTempoMedio[Data IDDTINICIOSTATUS];
                                       fChamadoTempoMedio[Data IDDTFINALSTATUS])) = 0;
               0;
               CALCULATE(SUM(dTempo[Binário Flag Dia da Semana]);
                           DATESBETWEEN(dTempo[Data];
                                       fChamadoTempoMedio[Data IDDTINICIOSTATUS];
                                       fChamadoTempoMedio[Data IDDTFINALSTATUS])) - 1)


Data IDDTINICIOSTATUS :=
	   DATEVALUE(MID(fChamadoTempoMedio[IDDTINICIOSTATUS];
           1, 4)
	& "/" &
        MID(fChamadoTempoMedio[IDDTINICIOSTATUS];
           5, 2) 
	& "/" &
       MID(fChamadoTempoMedio[IDDTINICIOSTATUS];
           7, 2)    )


Data IDDTFINALSTATUS :=
	   DATEVALUE(MID(fChamadoTempoMedio[IDDTFINALSTATUS];
           1, 4)
	& "/" &
        MID(fChamadoTempoMedio[IDDTFINALSTATUS];
           5, 2) 
	& "/" &
       MID(fChamadoTempoMedio[IDDTFINALSTATUS];
           7, 2)    )


Diferença Dias Status :=
	DATEDIFF(fChamadoTempoMedio[Data IDDTINICIOSTATUS], fChamadoTempoMedio[Data IDDTFINALSTATUS], DAY)


dstatuschamado_status_chamado :=
	LOOKUPVALUE(dStatusChamado[Status Chamado], dStatusChamado[IDSTATUSCHAMADO], fChamadoTempoMedio[IDSTATUSCHAMADOANTERIOR])


Agrupador de Status :=
	IF(fChamadoTempoMedio[dstatuschamado_status_chamado] = "New";
       "Backlog";
       IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ready for Dev";
           "Backlog";
           IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Backlog";
               "Backlog";
               IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag CodIFicação";
                   "Backlog";
                   IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Em Análise";
                       "Análise";
                       IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="In-Progress";
                           "CodIFicação";
                           IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Needs-CodeQA";
                               "CodIFicação";
                               IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="In-CodeQA";
                                   "CodIFicação";
                                   IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Needs Validation";
                                       "CodIFicação";
                                       IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Validation";
                                           "CodIFicação";
                                           IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Em CodIFicação";
                                               "CodIFicação";
                                               IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag Revisão";
                                                   "CodIFicação";
                                                   IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Em Revisão";
                                                       "CodIFicação";
                                                       IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag Sincronização";
                                                           "CodIFicação";
                                                           IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Em Sincronização";
                                                               "CodIFicação";
                                                               IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Em Validação Final";
                                                                   "CodIFicação";
                                                                   IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="In Sinc";
                                                                       "CodIFicação";
                                                                       IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Revisado";
                                                                           "CodIFicação";
                                                                           IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag CodIFicação (Retorno PML)";
                                                                               "Ag. CodIFicação (já iniciado)";
                                                                               IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag CodIFicação (Retorno Suporte)";
                                                                                   "Ag. CodIFicação (já iniciado)";
                                                                                   IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Not Approved";
                                                                                       "Ag. CodIFicação (já iniciado)";
                                                                                           IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Reprovado";
                                                                                               "Ag. CodIFicação (já iniciado)";
                                                                                               IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Aprovado / Ag Fechamento";
                                                                                                   "Ag. Lib. Versão";
                                                                                                   IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag PML";
                                                                                                       "Ag. PML";
                                                                                                       IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag Suporte";
                                                                                                           "Ag. Suporte";
                                                                                                           IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Waiting Support";
                                                                                                               "Ag. Suporte";
                                                                                                               IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag Versões";
                                                                                                                   "Ag. Versão";
                                                                                                                   IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Needs Version";
                                                                                                                       "Ag. Versão";
                                                                                                                       IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag Teste Master";
                                                                                                                           "Ag. Teste";
                                                                                                                           IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag Teste Local";
                                                                                                                               "Ag. Teste";
                                                                                                                               IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Ag Validação Final";
                                                                                                                                   "Ag. Teste";
                                                                                                                                   IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Needs-VerIFication";
                                                                                                                                       "Ag. Teste";
                                                                                                                                       IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Blocked";
                                                                                                                                           "Bloqueado";
                                                                                                                                           IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Em Teste Master";
                                                                                                                                               "Teste";
                                                                                                                                               IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="Em Teste Local";
                                                                                                                                                   "Teste";
                                                                                                                                                   IF(fChamadoTempoMedio[dstatuschamado_status_chamado]="In-Test";
                                                                                                                                                       "Teste";
                                                                                                                                                       "Pronto")                                                                                                                                                )                                                                                                                                            )                                                                                                                                        )                                                                                                                                    )                                                                                                                                )                                                                                                                            )                                                                                                                        )                                                                                                                    )                                                                                                                )                                                                                                            )                                                                                                        )                                                                                                    )                                                                                                )                                                                                            )                                                                                        )                                                                                    )                                                                                )                                                                            )                                                                        )                                                                    )                                                                )                                                            )                                                        )                                                    )                                                )                                            )                                        )                                    )                                )                            )                        )                    )                )            )        )


Data IDDTPRAZOSLA :=
	   DATEVALUE(MID(fChamadoBacklogZero[IDDTPRAZOSLA];
           1, 4)
	& "/" &
        MID(fChamadoBacklogZero[IDDTPRAZOSLA];
           5, 2) 
	& "/" &
       MID(fChamadoBacklogZero[IDDTPRAZOSLA];
           7, 2)    )


Prazo SLA Formatado :=
	IF(fChamadoBacklogZero[Data IDDTPRAZOSLA] == DATEVALUE("01/01/1900");
                       BLANK();
                       fChamadoBacklogZero[Data IDDTPRAZOSLA])


Período Atual :=
	IF(dTempoApuracao[Mês Atual] && dTempoApuracao[Binário Ano Atual];
    "Sim";
    "Não")


Mês Atual :=
	IF(dTempoApuracao[Código Mês] = dTempo[Mês Corrente]	
, 1 
, 0)


Binário Ano Atual :=
	IF(dTempoApuracao[Código Ano] = dTempo[Ano Corrente]	
, 1 
, 0)


Binário Flag Dia da Semana :=
	IF(dTempoApuracao[Flag Dia de Semana] = "S"	
, 1 
, 0)


Semana por Extenso :=
	[Descrição Semana Mês] //solicitação Carol


Semana que Passou ? :=
	IF([Número Semana Ano] < [Semana Atual] && [Código Ano] = YEAR(TODAY());
       "Sim";
       IF([Código Ano] <  YEAR(TODAY());
           "Sim";
           "Não")    )


Semana Atual ? :=
	   IF([Número Semana Ano] = [Semana Atual] && [Código Ano] = YEAR(TODAY());
       "Sim";
       "Não")


Próxima Semana ? :=
	IF([Número Semana Ano] > [Semana Atual] && [Código Ano] = YEAR(TODAY());
       "Sim";
       "Não")


Semana Por Extenso :=
	[Descrição Semana Mês] //solicitação Carol


Binário Flag Dia da Semana :=
	IF(dTempoApontamento[Flag Dia de Semana] = "S"	
, 1 
, 0 )


Quatidade Apontamento :=
	1


Média Horas Apontadas por Apontamento :=
	IF(AND(INT(MID(fChamadoApontamentoPerfilSeguranca[IDDATA]	
, 1 
, 4)) == YEAR(TODAY());
       INT(MID(fChamadoApontamentoPerfilSeguranca[IDDATA], 5, 2)) == MONTH(TODAY()));
   fChamadoApontamentoPerfilSeguranca[Horas Apontadas - Origem];
   0)


Sigla Equipe Usuário :=
	[Equipe Usuário]


