Goal Produtividade Individual :=
	   8


Usuário Name :=
	MID(USERNAME(), SEARCH("\\", USERNAME())	
, 1 
00)


Usuário Logado :=
	RIGHT([Usuário Name];
         (LEN([Usuário Name])-1))


Título - Seleção Cliente :=
	   IF(HASONEFILTER(dCliente[Sigla Cliente]);
     "CENÁRIO ➝ "&FILTERS(dCliente[Sigla Cliente]);
     "SELECIONE O CLIENTE")


Mês Corrente :=
	MONTH(TODAY())


Ano Corrente :=
	YEAR(TODAY())


DateTime Corrente :=
	 NOW()


Dia Corrente :=
	DAY(TODAY())


Aux Horas Apontadas no Mês :=
	CALCULATE(SUM(factRegistry[Horas Apontadas]);
               FILTER(dTempoRegistry, dTempoRegistry[Code Mês] == MONTH(TODAY()));
               FILTER(dTempoRegistry,  dTempoRegistry[Code Ano] == YEAR(TODAY())))


Soma Minutos :=
	FORMAT(SUM([Minutos]), "Standard")


Mean Horas Apontadas :=
	FORMAT(AVERAGE([Horas Apontadas]), "Standard")


Soma Horas :=
	FORMAT(SUM([Horas Apontadas]), "Standard")


Mean Minutos :=
	AVERAGE([Minutos])


Distinct Count IDUser :=
	FORMAT(DISTINCTCOUNT(factRegistry[IDUser]), "Standard")


Horas Potenciais :=
	FORMAT( factRegistry[Distinct Count IDUser] * [Horas Úteis Mês], "Standard")


Qtde Chamados Registry :=
	 DISTINCTCOUNT([IdRegistry])


Horas Apontadas Formatada :=
	FORMAT(SUM([Horas Apontadas]), "Standard")


Qtde Registry Formatada :=
	FORMAT(SUM([Qtde Registry]), "Standard")


Qtde Tarefa Projeto Serp :=
	DISTINCTCOUNT([IDTAREFASERP])


Qtde Projeto Serp :=
	DISTINCTCOUNT([IDPROJETOSERP])


Horas Apontadas no Mês :=
	FORMAT( CALCULATE([Aux Horas Apontadas no Mês], ALL(dTempoRegistry)), "Standard")


Aux Mean Horas Apontadas no Mês :=
	CALCULATE(AVERAGE(factRegistry[Mean Horas Apontadas por Registry]);
   FILTER(factRegistry, factRegistry[Mean Horas Apontadas por Registry] > 0))


Mean Horas Apontadas no Mês :=
	FORMAT( CALCULATE([Aux Mean Horas Apontadas no Mês], ALL(dTempoRegistry)), "Standard")


Qtde Backlog Consequência :=
	   CALCULATE(COUNT(factBacklog[IdRegistry]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] = "Defeito Consequência"))


Qtde A Vencer :=
	   CALCULATE(SUM(factBacklog[SLA a Vencer]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))  //1376 = Defeito Consequência


Qtde Backlog :=
	   CALCULATE(COUNT(factBacklog[IdRegistry]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))  //1376 = Defeito Consequência


Qtde Sem SLA :=
	   CALCULATE(SUM(factBacklog[Sem SLA]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))  //1376 = Defeito Consequência


Qtde Vencidos :=
	   CALCULATE(SUM(factBacklog[SLA Vencido]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))  //1376 = Defeito Consequência


Count of SLA a Vencer :=
	COUNTA([SLA a Vencer])


Qtde Rejeites Backlog :=
	CALCULATE(COUNT(factBacklog[IDORIUNDOREJEITE]);
       FILTER(factBacklog, factBacklog[IDORIUNDOREJEITE] = 1))


Soma de IDORIUNDOREJEITE :=
	SUM([IDORIUNDOREJEITE])


Mean Inputs - Diária :=
	   ROUND([Qtde Inputs aux]/[Dias Úteis Mês Apuração]	
, 1 
)


Mean Inputs - Dias Úteis :=
	   ROUND([Qtde Inputs aux]/[Dias Úteis Mês Apuração]	
, 1 
)


Mean Inputs - Mensal :=
	   ROUND([Qtde Inputs aux]/[Meses Contabilizados]	
, 1 
)


Qtde Inputs aux :=
	   CALCULATE(COUNT(factInput[IdRegistry]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência")) 


Qtde Inputs Consequência :=
	   CALCULATE(COUNT(factInput[IdRegistry]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] = "Defeito Consequência"))


Qtde Inputs :=
	   IF(ISBLANK([Qtde Inputs aux]);
   0;
   [Qtde Inputs aux])


Qtde Inputs Chegaram com SLA Perdido :=
	CALCULATE(SUM((factInput[SLA Venceu no Suporte])))


Qtde Rejeites Abertura :=
	CALCULATE(SUM(factInput[IDORIUNDOREJEITE]),  								 FILTER(factInput, factInput[IDORIUNDOREJEITE] = 1))


Qtde Negociações :=
	   COUNTROWS(factNegociado)


Mean Delivery Dev :=
	   [Qtde Delivery]/factOutput[distinctcount_IDDTAPURACAO_dIFf_blank]


Última Entrega :=
	   CALCULATE(MAX(factOutput[DateTime IDDTRESOLUCAO]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))


Mean Delivery - Mensal :=
	   ROUND([Qtde Delivery]/[Meses Contabilizados], 0)


Produtividade DEV :=
	   [Qtde Delivery]/[Qtde Analistas]


Produtividade Testers :=
	   [Qtde Delivery]/[Qtde Testers]


IAD :=
	   IF([Qtde Inputs aux] > 0;
       CALCULATE(DIVIDE([Qtde Delivery], [Qtde Inputs aux], 0));
       [Qtde Delivery])


SLA :=
	   DIVIDE([Qtde Delivery No Prazo];
         ([Qtde Delivery No Prazo] + [Qtde Delivery Fora Prazo]))


Produtividade :=
	   [Qtde Delivery]/[Qtde Analistas]


Mean Delivery - Diária :=
	   ROUND([Qtde Delivery]/[Dias Úteis Mês Apuração], 0)


Qtde Delivery :=
	   CALCULATE(COUNT(factOutput[IdRegistry]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))


Qtde Dias Última Entrega :=
	CALCULATE(DATEDIFF(MAX(factOutput[DateTime IDDTRESOLUCAO]), TODAY(), DAY);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))


Qtde Analistas :=
	   CALCULATE(DISTINCTCOUNT(factOutput[IDUserPROPRIETARIO]);
             FILTER(dRegistryCall,dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))


Qtde Delivery No Prazo :=
	   CALCULATE(COUNTROWS(factOutput);
             FILTER(factOutput, factOutput[No Prazo]=1);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))


Qtde Delivery Fora Prazo :=
	   CALCULATE(COUNTROWS(factOutput);
             FILTER(factOutput, factOutput[Fora Prazo] = 1);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência"))


Qtde Delivery Consequência :=
	   CALCULATE(COUNT(factOutput[IdRegistry]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] = "Defeito Consequência"))


Qtde Testers :=
	   CALCULATE(DISTINCTCOUNT(factOutput[IDTESTER]);
             FILTER(dRegistryCall, dRegistryCall[Tipo Chamado] <> "Defeito Consequência")) // unsigned, null e \'\' como Não Informado


Produtividade Mês :=
	DIVIDE([Qtde Delivery], [Dias Úteis Mês Apuração])


distinctcount_IDDTAPURACAO_diff_blank :=
	calculate( distinctcount(factOutput[IDDTAPURACAO Manipulado]), factOutput[IDDTAPURACAO Manipulado] <> BLANK())// original', "// Dias Úteis Mês = CALCULATE(sum('dCalendário'[Fim de Semana]))", '


Qtde Rejeites Entregues :=
	CALCULATE(SUM(factOutput[IDORIUNDOREJEITE]),  								 FILTER(factOutput, factOutput[IDORIUNDOREJEITE] = 1))


Soma Tempo Gasto :=
	SUM([Tempo Gasto])


Mean Tempo Gasto Status :=
	   CALCULATE(SUM(factTempoMedio[Tempo Gasto]) / [Qtde Itens Tempo Médio])


Tempo Médio Solução :=
	   AVERAGE(factTempoMedio[Tempo Gasto])


Qtde Itens Tempo Médio :=
	   DISTINCTCOUNT(factTempoMedio[IdRegistry])


Contagem Distinta de Status Chamado :=
	DISTINCTCOUNT([Status Chamado])


Qtde Backlog Zero :=
	   COUNTROWS(factBacklogZero)


Meses Contabilizados :=
	   CALCULATE(DISTINCTCOUNT(dTempoApuracao[Code Período]);
               FILTER(dTempoApuracao, dTempoApuracao[Code Ano] >= 2017);
               FILTER(dTempoApuracao, dTempoApuracao[Code Ano] < 2026))


Dias Úteis Mês Apuração :=
	CALCULATE(SUM(dTempoApuracao[Bynary Flag Dia da Semana]);
             FILTER(dTempoApuracao, dTempoApuracao[Code Ano] >= 2017);
             FILTER(dTempoApuracao, dTempoApuracao[Data Apuração] < TODAY());
             FILTER(dTempoApuracao, dTempoApuracao[Flag Feriado] = "N"))


Semana Current :=
	WEEKNUM(TODAY())


Próxima Semana :=
	WEEKNUM(today())+1


Horas Úteis Mês :=
	[Dias Úteis Mês] * 8


Dias Úteis Mês :=
	CALCULATE(SUM(dTempoRegistry[Bynary Flag Dia da Semana]);
             FILTER(dTempoRegistry, dTempoRegistry[Code Ano] >= 2017);
             FILTER(dTempoRegistry, dTempoRegistry[Data Registry] < TODAY());
             FILTER(dTempoRegistry, dTempoRegistry[Flag Feriado] = "N"))


Mean Horas Apontadas no Mês factRegistryPerfilSeguranca :=
	CALCULATE(AVERAGE(factRegistry[Mean Horas Apontadas por Registry]), ALL(factRegistry))


Horas Apontadas no Mês factPerfilSeguranca :=
	CALCULATE(SUM(factRegistry[Horas Apontadas]);
             FILTER(dTempoRegistry,  dTempoRegistry[Code Mês] == MONTH(TODAY())), FILTER(dTempoRegistry,  dTempoRegistry[Code Ano] == YEAR(TODAY())))


Soma Minutos factRegistryPerfilSeguranca :=
	SUM([Minutos])


Mean Horas Apontadas factRegistryPerfilSeguranca :=
	AVERAGE([Horas Apontadas - Origem])


Soma Horas factRegistryPerfilSeguranca :=
	SUM([Horas Apontadas - Origem])


Mean Minutos factRegistryPerfilSeguranca :=
	AVERAGE([Minutos])


Horas Potenciais factRegistryPerfilSeguranca :=
	factRegistry[Distinct Count IDUser] * [Horas Úteis Mês]


Qtde Chamados Registry factRegistryPerfilSeguranca :=
	DISTINCTCOUNT([IdRegistry])


